.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. manna_qt test_manna_qt
clean: FORCE
	$(MAKE) -C .. manna_qt_clean test_manna_qt_clean
check: FORCE
	$(MAKE) -C .. test_manna_qt_check
manna-qt manna-qt.exe: FORCE
	 $(MAKE) -C .. manna_qt
